// sim: the authoritative systems by domain: the home planet (generated, with its
// deviations) and the Phase 0 sandbox. May import: kernel, rules, gen. See README.md and docs/architecture/universe-architecture.md.
export {
  BLESSING_EVENT,
  CELL,
  CELLS,
  CLASSES,
  EXODUS_EVENT,
  FLOODPLAIN,
  FLOOD_EVENT,
  ToyMarket,
  ToyMemory,
  ToyPopulation,
  cellRef,
  floodplainRef,
  makeToyWorld,
  type ToyOptions,
} from "./sandbox/toy.ts";
export {
  HomePlanet,
  homePlanet,
  makePlanetWorld,
  type PlanetWorldOptions,
} from "./planet/store.ts";
export { COLS, Province, ROWS, capacity, row, type Capacity } from "./population/model.ts";
export {
  HistoryStore,
  PopulationStore,
  SETTLEMENT,
  SettlementStore,
  type Flow,
  type Settlement,
  type YearSummary,
} from "./population/stores.ts";
export {
  POPULATION_EVENTS,
  VILLAGE_SIZE,
  installPopulation,
  occupationTargets,
  marketsOf,
  populationContext,
  provinceCapacity,
  regionOf,
  regionReady,
  support,
  type PopulationContext,
} from "./population/systems.ts";
export {
  FIRST_PEOPLE,
  SPREAD,
  chooseHome,
  makePopulationWorld,
  type PopulationWorldOptions,
} from "./population/world.ts";
export {
  GOOD_COUNT,
  LEDGER,
  MARKET_GOOD,
  MARKET_YEARS,
  PRICE_YEARS,
  Market,
  MarketStore,
  marketGoodRef,
  type LedgerLine,
  type MarketYear,
  type PricePoint,
  type TradeFlow,
} from "./economy/market.ts";
export {
  ECONOMY_EVENTS,
  HAUL_PER_100KM,
  economyYear,
  installEconomy,
  metalYear,
} from "./economy/systems.ts";
export {
  ACT_EVENTS,
  ACT_KINDS,
  ACT_STRENGTH,
  ActStore,
  actsOf,
  type Act,
  type ActArgs,
  type ActKind,
} from "./acts/acts.ts";
export {
  HAND_EVENTS,
  HandStore,
  bandOfAge,
  handOf,
  installHand,
  type Agent,
  type Window,
} from "./hand/hand.ts";
export {
  CultureStore,
  PUSHES,
  WAY,
  WAY_TRAITS,
  cultureOf,
  cultureYear,
  type Nudge,
  type Ways,
  type WayTrait,
} from "./culture/culture.ts";
export {
  LAW,
  LEADERSHIP,
  POLITY,
  POLITY_EVENTS,
  PolityStore,
  REALM_WORDS,
  SUCCESSION,
  governmentKey,
  institutionsOf,
  installPolities,
  politiesOf,
  polityYear,
  realmName,
  type Discontent,
  type Polity,
  type Ruler,
} from "./polity/polity.ts";
export {
  BELIEF_EVENTS,
  BeliefStore,
  DEITIES,
  FAITH,
  TENETS,
  beliefOf,
  beliefYear,
  installBelief,
  type Belief,
  type Faith,
  type Tenet,
} from "./belief/belief.ts";
export {
  LEARNING,
  LORE_EVENTS,
  LORE_PACE,
  LoreStore,
  installLore,
  knows,
  loreOf,
  loreYear,
  type Known,
} from "./lore/lore.ts";
export {
  DIPLOMACY_EVENTS,
  DiplomacyStore,
  PACT,
  RELATION,
  RIVALRY,
  diplomacyOf,
  diplomacyYear,
  installDiplomacy,
  relationRef,
  type Relation,
  type Term,
} from "./diplomacy/diplomacy.ts";
export {
  WAR,
  WAR_EVENTS,
  WarStore,
  installWar,
  strengthOf,
  warYear,
  warsOf,
  type Battle,
  type War,
} from "./war/war.ts";
