// sim: the authoritative systems by domain: the home planet (generated, with its
// deviations) and the Phase 0 sandbox. May import: kernel, rules, gen. See README.md and docs/architecture/universe-architecture.md.
export {
  BLESSING_EVENT,
  CELL,
  CELLS,
  CLASSES,
  EXODUS_EVENT,
  FLOODPLAIN,
  FLOOD_EVENT,
  ToyMarket,
  ToyMemory,
  ToyPopulation,
  cellRef,
  floodplainRef,
  makeToyWorld,
  type ToyOptions,
} from "./sandbox/toy.ts";
export {
  HomePlanet,
  homePlanet,
  makePlanetWorld,
  type PlanetWorldOptions,
} from "./planet/store.ts";
export {
  COLS,
  Province,
  ROWS,
  capacity,
  coastal,
  livable,
  row,
  type Capacity,
} from "./population/model.ts";
export {
  HistoryStore,
  LIVING_MEMORY,
  livingMemory,
  PopulationStore,
  SETTLEMENT,
  SettlementStore,
  type Flow,
  type Settlement,
  type YearSummary,
} from "./population/stores.ts";
export {
  adults,
  mouths,
  POPULATION_EVENTS,
  VILLAGE_SIZE,
  installPopulation,
  livableFor,
  occupationTargets,
  marketsOf,
  populationContext,
  provinceCapacity,
  regionOf,
  regionReady,
  REGION_SIZE,
  PROVINCE_TILE_KM,
  prepareSites,
  hallsShare,
  spaceSteps,
  sitesReady,
  support,
  type PopulationContext,
} from "./population/systems.ts";
export {
  FIRST_PEOPLE,
  SPREAD,
  chooseHome,
  makePopulationWorld,
  type PopulationWorldOptions,
} from "./population/world.ts";
export {
  GOOD_COUNT,
  LEDGER,
  MARKET_GOOD,
  MARKET_YEARS,
  PRICE_YEARS,
  Market,
  MarketStore,
  marketGoodRef,
  type LedgerLine,
  type MarketYear,
  type PricePoint,
  type TradeFlow,
} from "./economy/market.ts";
export {
  ECONOMY_EVENTS,
  HAUL_PER_100KM,
  economyYear,
  installEconomy,
  metalYear,
  powerOf,
  toolMetal,
  whyNot,
  type ToolMetal,
} from "./economy/systems.ts";
export {
  ACT_EVENTS,
  ACT_KINDS,
  ACT_STRENGTH,
  ActStore,
  actsOf,
  type Act,
  type Crater,
  type ActArgs,
  type ActKind,
} from "./acts/acts.ts";
export {
  GONE_KEPT,
  HAND_EVENTS,
  HandStore,
  PERSON_TRAITS,
  PIOUS_BLESSING,
  TRAIT_ANEW,
  TRAIT_INHERITED,
  TRAIT_SHARE,
  TRAIT_WEIGHT,
  TRAIT_WORK,
  bandOfAge,
  drawTraits,
  handOf,
  installHand,
  opposedTo,
  pairUp,
  traitWeight,
  workWeights,
  type Agent,
  type Gone,
  type PersonTrait,
  type Window,
} from "./hand/hand.ts";
export {
  CultureStore,
  PUSHES,
  WAY,
  WAY_TRAITS,
  cultureOf,
  cultureYear,
  type Nudge,
  type Ways,
  type WayTrait,
} from "./culture/culture.ts";
export {
  APART,
  LANGUAGE,
  LANGUAGE_EVENTS,
  LanguageStore,
  NEARER,
  foundLanguages,
  installLanguages,
  languagesOf,
  languagesYear,
  type Language,
} from "./culture/languages.ts";
export { lifeOf, peopleLife } from "./population/life.ts";
export { MOST_SEA_STEPS, SEA_STEPS, seaRange, seaReach, seaSteps } from "./economy/sea.ts";
export {
  AIR_EVENTS,
  AirStore,
  CARBON_PER_FOREST_KM2,
  CARBON_PER_FUEL,
  FIRST_CARBON,
  SENSITIVITY,
  airOf,
  airYear,
  heatYield,
  installAir,
  rainShift,
  smokeIn,
  warmingOf,
  type Air,
} from "./climate/air.ts";
export {
  LAW,
  LEADERSHIP,
  POLITY,
  POLITY_EVENTS,
  PolityStore,
  REALM_WORDS,
  SEA_CROSSING,
  SUCCESSION,
  governmentKey,
  institutionsOf,
  installPolities,
  politiesOf,
  polityYear,
  raiseRealm,
  realmName,
  type Discontent,
  type Polity,
  type Ruler,
} from "./polity/polity.ts";
export {
  BELIEF_EVENTS,
  BeliefStore,
  DEITIES,
  FAITH,
  TENETS,
  beliefOf,
  beliefYear,
  installBelief,
  type Belief,
  type Faith,
  type Tenet,
} from "./belief/belief.ts";
export {
  LEARNING,
  LORE_EVENTS,
  LORE_PACE,
  LoreStore,
  installLore,
  knows,
  loreOf,
  loreYear,
  type Known,
} from "./lore/lore.ts";
export {
  DIPLOMACY_EVENTS,
  DiplomacyStore,
  PACT,
  RELATION,
  RIVALRY,
  diplomacyOf,
  diplomacyYear,
  installDiplomacy,
  relationRef,
  type Relation,
  type Term,
} from "./diplomacy/diplomacy.ts";
export {
  WAR,
  WAR_EVENTS,
  WEARY_YEARS,
  WarStore,
  installWar,
  fieldedOf,
  fieldedParts,
  frontier,
  strengthOf,
  warYear,
  warsOf,
  type Battle,
  type War,
} from "./war/war.ts";
export {
  BLOCKS,
  BLOCK_M,
  CITY_EVENTS,
  CITY_SIZE,
  CityStore,
  USE,
  USES,
  blockAt,
  citiesOf,
  cityYear,
  installCities,
  layout,
  type City,
} from "./city/city.ts";
export { BLESSING, LOCAL_ACT_EVENTS, agentName, installLocalActs } from "./acts/local.ts";
export {
  FORTUNE,
  PEOPLE_ACT_EVENTS,
  REGARD,
  RISEN,
  SETTLERS,
  installPeopleActs,
  settlersFrom,
  type ConvertArgs,
  type LandArgs,
  type PairArgs,
  type RealmArgs,
} from "./acts/peoples.ts";
export { DISASTER, DISASTER_EVENTS, installDisasters } from "./acts/disasters.ts";
export {
  WAYS_ACT_EVENTS,
  WAYS_PUSH,
  installWaysActs,
  type FaithArgs,
  type TongueArgs,
  type WaysArgs,
} from "./acts/ways.ts";
export {
  GROUPS,
  interestsOf,
  pressure,
  swayOf,
  type Demand,
  type Group,
  type Interest,
} from "./polity/interests.ts";
export {
  DESIGN,
  DESIGN_EVENTS,
  DesignStore,
  designsOf,
  worksFor,
  hostFor,
  houseFor,
  installDesigns,
  landMaterials,
  type Design,
} from "./design/design.ts";
export {
  ECOLOGY_EVENTS,
  EcologyStore,
  FLOCK_LOSS,
  ecologyOf,
  ecologyYear,
  firstForest,
  grainLost,
  hunterOf,
  installEcology,
  lineageOf,
  living,
  stepWilds,
  waterYield,
  watersOf,
  wildsOf,
  type Wilds,
} from "./ecology/ecology.ts";
export {
  COLONISTS,
  COLONY_GAP,
  COLONY_SHARE,
  CREW_TONNES,
  FLIGHT_PACE,
  MACHINES_PER_COST,
  PROGRAM_SHARE,
  SATELLITE_TONNES,
  SETTLER_TONNES,
  SPACE_EVENTS,
  STATION_TONNES,
  SpaceStore,
  installSpace,
  launcherOfRealm,
  prospects,
  spaceOf,
  spaceYear,
  type Program,
} from "./space/space.ts";
export { StarSiteStore, lightSteps, starSitesOf, type StarSite } from "./space/stars.ts";
export {
  ABOARD,
  STARSHIP_MACHINES,
  VOYAGE_EVENTS,
  VOYAGE_GAP,
  clusterOf,
  installVoyages,
  voyageTarget,
  voyageYear,
  worldsOf,
} from "./space/voyages.ts";
export {
  CONTACT_EVENTS,
  ContactStore,
  civilizationsNear,
  contactYear,
  contactsOf,
  installContact,
  type Contact,
} from "./space/contact.ts";
export {
  FLEET_MACHINES,
  STARWAR,
  STARWAR_EVENTS,
  STARWAR_PACE,
  StarWarStore,
  installStarWars,
  starWarYear,
  starWarsOf,
  type StarWar,
} from "./space/starwar.ts";
export {
  GREAT_ACT_EVENTS,
  GREAT_ACT_STRENGTH,
  GreatActStore,
  divineWarming,
  greatActsOf,
  installGreatActs,
  starHazard,
  type GreatAct,
} from "./acts/great.ts";
