// rules: data tables and their schemas — generation priors now; commodities,
// principles, body-plan primitives and the rest as later milestones need them.
// May import: kernel. See README.md and docs/architecture §34.
export {
  ENGINE_GAIN,
  FOODS,
  FORAGER_HIDES,
  FUELS,
  G,
  GLUT_YEARS,
  GOODS,
  HERD_GOODS,
  HOME_MADE,
  MACHINE_GAIN,
  PORTERAGE_PER_PERSON,
  POWER,
  RECIPES,
  TOOL_GAIN,
  TOOL_USERS,
  TRADER_CAPACITY,
  WANTS,
  type Good,
  type Recipe,
} from "./goods.ts";
export { EARTHLIKE, OPEN, PRIORS, type Prior, type Range } from "./priors.ts";
export {
  CLADES,
  affordancesOf,
  bodyOf,
  bodyWords,
  type Affordances,
  type Bearing,
  type BodyPlan,
  type Clade,
  type Conditions,
  type Diet,
  type Manipulator,
  type Medium,
  type Sense,
  type Skin,
} from "./bodies.ts";
export {
  EFFECTS,
  PRINCIPLES,
  PRINCIPLE_INDEX,
  principle,
  type Drivers,
  type Effect,
  type Principle,
} from "./principles.ts";
export {
  BANDS,
  FEMALE,
  HUMANLIKE,
  MALE,
  OCC,
  OCCUPATIONS,
  PRODUCTIVITY,
  SEXES,
  bandWidth,
  type LifeHistory,
  type Occupation,
} from "./species.ts";
export {
  HOST_AXES,
  HOST_ROLES,
  HOUSE_AXES,
  HOUSE_ROLES,
  WORKS_AXES,
  WORKS_ROLES,
  MATERIAL,
  MATERIALS,
  REALIZATIONS,
  compose,
  designWords,
  hostPower,
  performanceOf,
  realization,
  roofPitch,
  worth,
  type Axis,
  type Doctrine,
  type Material,
  type Part,
  type Performance,
  type Realization,
  type Role,
} from "./designs.ts";
