// view: pure view-spec builders — simulation frames to what is drawn and shown.
// May import: kernel, rules, bridge. See README.md and docs/architecture §28.
export {
  CELL_RADIUS,
  CLASS_COLORS,
  CLASS_NAMES,
  PEOPLE_PER_FIGURE,
  RING_RADIUS,
  cellAt,
  cellCenter,
  priceColor,
  sandboxSpec,
  type CellSpec,
  type CrowdSpec,
  type Rgb,
  type SandboxSpec,
} from "./sandbox.ts";
export {
  DEPOSIT_COLORS,
  LENSES,
  LENS_ICONS,
  STANDING_COLORS,
  WAR_COLORS,
  biomeColor,
  LENS_NAMES,
  BELIEF_COLORS,
  beliefColor,
  globeColors,
  globeRadius,
  lensLegend,
  litColors,
  type Legend,
  type Lens,
  type Lit,
} from "./globe.ts";
export {
  ACT_PARTS,
  ACT_PART_LOOK,
  actBits,
  placeActs,
  type ActBit,
  type ActPart,
  type PlacedAct,
} from "./acts.ts";
export {
  REGION_LENSES,
  REGION_LENS_NAMES,
  REGION_RELIEF,
  regionColors,
  regionFromGlobe,
  regionHeights,
  regionTrees,
  type RegionTree,
  type RegionLens,
} from "./region.ts";
export {
  ACTIVITY,
  ACTIVITY_WORDS,
  BODY_R,
  SIGNS,
  TASKS,
  houseLook,
  keepApart,
  momentOf,
  villageSolids,
  personGroup,
  sayOf,
  treesOf,
  type Activity,
  type HouseLook,
  type Moment,
  type Task,
  type Tree,
} from "./village.ts";
export { STRIDES, bobOf, limbPitch } from "./motion.ts";
export { BLINK, DASH, FAR, SMOOTH, present, type Presence } from "./presence.ts";
export {
  BEYOND,
  flightAt,
  towardOnFlat,
  towardOnGlobe,
  zoomStep,
  type OrbitView,
  type ZoomState,
} from "./zoom.ts";
export {
  freeLook,
  freeStep,
  orbitOf,
  type FreeInput,
  type FreeRules,
  type FreeState,
} from "./free.ts";
export {
  DAWN,
  DAWN_WORDS,
  ageColors,
  ageWords,
  dropOf,
  formingColors,
  paradeOf,
  type CellPart,
  type Dawn,
  type Drop,
  type OnStage,
} from "./genesis.ts";
export {
  BATTLE_ROUND,
  MARCH,
  battleFigures,
  battleFront,
  battleOf,
  counterWords,
  holdShape,
  hostShape,
  landBattle,
  landColumn,
  landShape,
  landWars,
  loopSize,
  rides,
  warPaths,
  warTokens,
  type BattleFigure,
  type ColumnMark,
  type LandSoldier,
  type LandWars,
  type Soldier,
  type WarPath,
  type WarPaths,
  type WarToken,
} from "./war.ts";
export { hallCells, hallDomes } from "./halls.ts";

export {
  HAIRS,
  SHEEN,
  carryWords,
  hairOf,
  homeDetail,
  lamplight,
  metalOf,
  type HomePiece,
} from "./detail.ts";
export {
  CARRIES,
  MATERIALS,
  cartAt,
  factoryPieces,
  itemParts,
  materialColor,
  minePieces,
  smokeAt,
  toolHead,
  travellerAt,
  wellPieces,
  type Carry,
  type ItemPart,
  type Material,
  type Mine,
  type MinePiece,
  type Puff,
  type Road,
} from "./work.ts";
export {
  TRAFFIC_PACE,
  beastsAt,
  birdsAt,
  coatOf,
  defaultBody,
  doingOf,
  faunaOf,
  fishAt,
  type BeastNow,
  type BirdNow,
  type Coat,
  type Fauna,
  type FaunaSpecies,
  type FishNow,
  type Traffic,
} from "./fauna.ts";
export { clearOf, dryAt, keepOut, villageGround, type Ground, type Solid } from "./ground.ts";
export {
  BEAST_SCALE,
  MOST_OF_TONE,
  MOST_PARTS,
  buildBody,
  posed,
  strideOf,
  type BeastPart,
  type Built,
  type Pose,
} from "./creature.ts";
export {
  figureOf,
  paceOf,
  type Figure,
  type FigureBody,
  type FigurePart,
  type PartShape,
} from "./figure.ts";
export {
  HOME_DISTANCE,
  STAR_SIZE,
  bodyColor,
  bodyFacts,
  bodySize,
  orbitRings,
  routeWords,
  skyMarks,
  systemExtent,
  systemSpec,
  type SkyMarks,
  type SystemSpot,
} from "./system.ts";
export {
  LY_SCALE,
  clusterSpec,
  clusterWords,
  starColor,
  voyageMarks,
  type FleetHead,
  type Rgb3,
  type VoyageMark,
} from "./cluster.ts";
export { bandsOf, groundOf, worldColors } from "./worlds.ts";
export {
  GALAXY_LY,
  galaxyPoints,
  homeOf,
  lyFromHome,
  starWords,
  type GalaxyPoints,
} from "./galaxy.ts";
export { EYES, GROUP_COLORS, SKIN, clothes } from "./dress.ts";
export { nameShape, namesThatFit, withinName, type LaidName, type NameShape } from "./mapnames.ts";
